
raw_fixed:
	RSA_BITS=1024 RSA_MODE=raw_fixed python demo_rsa04.py

raw_len:
	RSA_BITS=1024 RSA_MODE=raw_len   python demo_rsa04.py

rand_fixed:
	RSA_BITS=1024 RSA_MODE=rand_fixed python demo_rsa04.py

rand_len:
	RSA_BITS=1024 RSA_MODE=rand_len  python demo_rsa04.py
